/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminLobbiesRouteImport } from './routes/admin/lobbies'
import { Route as AdminGamesRouteImport } from './routes/admin/games'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLobbiesRoute = AdminLobbiesRouteImport.update({
  id: '/admin/lobbies',
  path: '/admin/lobbies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/admin/games',
  path: '/admin/games',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/lobbies': typeof AdminLobbiesRoute
  '/admin/rooms': typeof AdminRoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/lobbies': typeof AdminLobbiesRoute
  '/admin/rooms': typeof AdminRoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/lobbies': typeof AdminLobbiesRoute
  '/admin/rooms': typeof AdminRoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/games' | '/admin/lobbies' | '/admin/rooms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/games' | '/admin/lobbies' | '/admin/rooms'
  id: '__root__' | '/' | '/admin/games' | '/admin/lobbies' | '/admin/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminLobbiesRoute: typeof AdminLobbiesRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lobbies': {
      id: '/admin/lobbies'
      path: '/admin/lobbies'
      fullPath: '/admin/lobbies'
      preLoaderRoute: typeof AdminLobbiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/admin/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminLobbiesRoute: AdminLobbiesRoute,
  AdminRoomsRoute: AdminRoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
